### PR TITLE
Fix the bug in Transaction.isSorobanTransaction to accommodate BumpFootprintExpirationOperation.

### LINKED ISSUE #517: There is a typo in Transaction.isSorobanData.
### What version are you using?
[0.41.0-beta.2](https://github.com/stellar/java-stellar-sdk/releases/tag/0.41.0-beta.2)

### What did you do?

```java
  @Test
  public void testIsSorobanTransactionBumpFootprintExpirationOperation() {
    KeyPair source =
        KeyPair.fromSecretSeed("SCH27VUZZ6UAKB67BDNF6FA42YMBMQCBKXWGMFD5TZ6S5ZZCZFLRXKHS");

    Account account = new Account(source.getAccountId(), 2908908335136768L);
    String contractId = "CDYUOBUVMZPWIU4GB4XNBAYL6NIHIMYLZFNEXOCDIO33MBJMNPSFBYKU";
    SorobanTransactionData sorobanData =
        new SorobanDataBuilder()
            .setReadOnly(
                Collections.singletonList(
                    new LedgerKey.Builder()
                        .discriminant(LedgerEntryType.CONTRACT_DATA)
                        .contractData(
                            new LedgerKey.LedgerKeyContractData.Builder()
                                .contract(new Address(contractId).toSCAddress())
                                .key(Scv.toLedgerKeyContractInstance())
                                .durability(ContractDataDurability.PERSISTENT)
                                .bodyType(ContractEntryBodyType.DATA_ENTRY)
                                .build())
                        .build()))
            .build();
    BumpFootprintExpirationOperation operation =
        BumpFootprintExpirationOperation.builder().ledgersToExpire(4096L).build();
    Transaction transaction =
        new Transaction(
            AccountConverter.enableMuxed(),
            account.getAccountId(),
            Transaction.MIN_BASE_FEE,
            account.getIncrementedSequenceNumber(),
            new org.stellar.sdk.Operation[] {operation},
            null,
            new TransactionPreconditions(
                null, null, BigInteger.ZERO, 0, new ArrayList<SignerKey>(), null),
            sorobanData,
            Network.TESTNET);
    assertTrue(transaction.isSorobanTransaction());
  }
```

### What did you expect to see?
the above test passed

### What did you see instead?
the above test failed

### Note
This is because `BumpSequenceOperation` should be changed to `BumpFootprintExpirationOperation`.

https://github.com/stellar/java-stellar-sdk/blob/d6379e961557ac3d86609c26141d2c0dad376ac3/src/main/java/org/stellar/sdk/Transaction.java#L405

### PR DESCRIPTION
**Pull request by overcat**
Fix #517 

We need to release a new version, and I have already included it in 96eebcd0b2b95785300ee051a04e01fabe135e46.

Due to the instability of Android testing on API 33 / GitHub Action, I have removed it from the deploy needs. I need some time to investigate this issue as it runs fine on my local machine.

### CODE REVIEW

File: src/test/java/org/stellar/sdk/TransactionTest.java [hunk 1]
```diff
@@ -260,4 +287,164 @@ public void testConstructorWithSorobanData() throws IOException {
...
+    Account account = new Account(source.getAccountId(), 2908908335136768L);
+    BumpSequenceOperation operation = new BumpSequenceOperation.Builder(0L).build();
+
+    Transaction transaction =
+        new Transaction(
+            AccountConverter.enableMuxed(),
+            account.getAccountId(),
+            Transaction.MIN_BASE_FEE,
+            account.getIncrementedSequenceNumber(),
+            new org.stellar.sdk.Operation[] {operation, operation},
```
Comment (sreuland) [inline src/test/java/org/stellar/sdk/TransactionTest.java:442]: i think only single op needed in tx correct? otherwise isSorobanTransaction=false, but for non-tested reason, i.e. it's more than one op, it won't validate op instance mismatch yet.

**Review by sreuland — APPROVED** [review]
great test coverage to assert fix.

File: src/test/java/org/stellar/sdk/TransactionTest.java (hunk 1 above)
Comment (overcat) [reply src/test/java/org/stellar/sdk/TransactionTest.java:442]: This test is to verify that a transaction containing multiple operations is not a soroban transaction. You can take a look at https://github.com/stellar/java-stellar-sdk/pull/518/files#diff-0114ab460186855a151f487001dae40013372c8430be55eeebdb6e24bfc12705R448
```java
assertFalse(transaction.isSorobanTransaction());
```

Comment (sreuland) [reply src/test/java/org/stellar/sdk/TransactionTest.java:442]: there is already another test for asserting multi-op - `testIsSorobanTransactionMultiOperations` outcome, I think this test was intending to exercise a non-multi op code path but an incorrect op type, which seemed to be the intent, just pass one `operation` and it should verify same false outcome.

Comment (overcat) [reply src/test/java/org/stellar/sdk/TransactionTest.java]: I'm sorry, I made a mistake. I have already corrected it. 🤦

**Comment by overcat** [comment]
Hi @sreuland @tamirms, can you help me publish a new release?

**Comment by sreuland** [comment]
> Hi @sreuland @tamirms, can you help me publish a new release?

yes, it's ok for me to merge this PR to `soroban` correct?

**Comment by sreuland** [comment]
@overcat , [0.41.0-beta.3](https://github.com/stellar/java-stellar-sdk/releases/tag/0.41.0-beta.3) was published, thank you!
