### PR TITLE
fix the issue of unable to parse liquidity_pool_revoked effect properly.

### LINKED ISSUE #393: When the query effect data type returns 95, there will be a gson parsing exception
Hello, I found a bug in version 0.29.0. When the data type returns LiquidityPoolRevokedEffectResponse, the return parameter reserves_revoked should be accepted as an array instead of entity classes.

### PR DESCRIPTION
**Pull request by overcat**
fix #393 

Due to user demand for this fix, let's release it on the master branch.

~~Let's merge #522 first.~~

### CODE REVIEW

File: src/main/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilder.java
Comment (overcat) [inline src/main/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilder.java:1]: This file is irrelevant to this PR, please ignore it.

File: src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java
Comment (overcat) [inline src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java:1]: This file is irrelevant to this PR, please ignore it.

Comment (sreuland) [reply src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java:1]: what issue or pr is it related to, this will land on master, is there a way to rebase the source branch to get cleaner change set?

**Comment by sreuland** [comment]
It looks like this pr is also doing the release prep, as it has notes and version bump for 0.40.1, just to confirm, you intend to merge this and #522 to master and then we just tag release off master which would be an effective changeset of just those two, as nothing else has merged to master since 0.40.0 correct?

File: src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java
Comment (overcat) [reply src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java:1]: This is because when we merged #426, #426 was not formatted (it is a very "old" PR.). If necessary, I can create another PR to format it.

**Comment by overcat** [comment]
> It looks like this pr is also doing the release prep, as it has notes and version bump for 0.40.1, just to confirm, you intend to merge this and #522 to master and then we just tag release off master which would be an effective changeset of just those two, as nothing else has merged to master since 0.40.0 correct?

Yes, let's merge these two PRs and then release it on the **master** branch. I have updated the changelog to include all the changes.

File: src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java
Comment (sreuland) [reply src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java:1]: ok, I see it mentioned in the changelog notes, which is great, thanks!

File: src/test/java/org/stellar/sdk/responses/EffectDeserializerTest.java [hunk 1]
```diff
@@ -1318,4 +1321,96 @@ public void testDeserializeLiquidityPoolTradeEffect() {
         new AssetAmount(
             create("ARST:GB7TAYRUZGE6TVT7NHP5SMIZRNQA6PLM423EYISAOAP3MKYIQMVYP2JO"), "1.0000000"));
   }
+
```
Comment (sreuland) [inline src/test/java/org/stellar/sdk/responses/EffectDeserializerTest.java:1324]: great test coverage!

**Review by sreuland — APPROVED** [review]
