### PR TITLE
Use `Price` instead of `String` to represent prices.

### LINKED ISSUE #292: Some envelopes with buy/sell offers decoded incorrectly
###  What version are you using?

0.18.0

### What did you do?

```java

@Test
    public void offerWithPriceFractionsNotInLowestTerms() throws IOException {

        //numerator is 10000000
        //denominator is 50
        //decode transaction should maintain same values without attempting to reduce fraction to its lowest terms.
        String envelope = "AAAAAgAAAADyfFnjmoCWKyzSBOiKQzP3K8l5z5/uF+pQ2ruXEh9+qAAAAGQADM4dAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAK0KBx2qoQ+o9JNLweoxVw6UYcRUzyKQH/ExRjJ63HEBAAAAAwAAAAFCVEMAAAAAAC8/6Fx60RqPg0dQCYSIhede3rzDSAWgvrFAsTn0LiI8AAAAAAAAAAAAAAAzAJiWgAAAADIAAAAAAAAAAAAAAAAAAAAA";

        AbstractTransaction txn = org.stellar.sdk.Transaction.fromEnvelopeXdr(envelope, Network.TESTNET);

        String returnedEnvelope = txn.toEnvelopeXdrBase64();

        assertEquals(envelope, returnedEnvelope);

    }

```

### What did you expect to see?

Test passed. Decoding and encoding the envelope XDR should reproduce the same envelope XDR.

### What did you see instead?

Test failed.  Decoding and encoding the envelope XDR reproduced a different envelope XDR.

The original envelope had price n = 10000000 and d = 50. The regenerated envelope reduced the price fractions to its lowest terms with n = 200000 and d = 1. Though correct, this generates an XDR which is different from the original XDR.

Prices should be represented internally as fractions, not strings.

### PR DESCRIPTION
**Pull request by overcat**
Fix #292

### CODE REVIEW

File: src/main/java/org/stellar/sdk/CreatePassiveSellOfferOperation.java [hunk 1]
```diff
@@ -109,13 +105,25 @@ public Builder(
...
       this.price = price;
     }
 
+    /** An alias for {@link Builder#Builder(Asset, Asset, String, Price)} */
+    public Builder(
+        @NonNull Asset selling,
+        @NonNull Asset buying,
+        @NonNull String amount,
+        @NonNull String price) {
+      this.selling = selling;
```
Comment (sreuland) [inline src/main/java/org/stellar/sdk/CreatePassiveSellOfferOperation.java:121]: for consideration, convert and delegate to the other method rather than implement locally:
```
builder(selling, buying, amount, Price.fromString(price))
```

File: src/main/java/org/stellar/sdk/ManageBuyOfferOperation.java [hunk 2]
```diff
@@ -124,13 +123,25 @@ public Builder(
...
       this.price = price;
     }
 
+    /** An alias for {@link Builder#Builder(Asset, Asset, String, Price)} */
+    public Builder(
+        @NonNull Asset selling,
+        @NonNull Asset buying,
+        @NonNull String amount,
+        @NonNull String price) {
+      this.selling = selling;
```
Comment (sreuland) [inline src/main/java/org/stellar/sdk/ManageBuyOfferOperation.java:139]: same overloaded constructor pattern could be used here, convert and invoke the main constructor instead:

```
this(selling, buying, amount, Price.fromString(price))

```

File: src/main/java/org/stellar/sdk/ManageSellOfferOperation.java [hunk 3]
```diff
@@ -124,13 +123,25 @@ public Builder(
...
       this.price = price;
     }
 
+    /** An alias for {@link Builder#Builder(Asset, Asset, String, Price)} */
+    public Builder(
+        @NonNull Asset selling,
+        @NonNull Asset buying,
+        @NonNull String amount,
+        @NonNull String price) {
+      this.selling = selling;
```
Comment (sreuland) [inline src/main/java/org/stellar/sdk/ManageSellOfferOperation.java:139]: same as prior comment - https://github.com/stellar/java-stellar-sdk/pull/554/files#r1379165851

File: src/test/java/org/stellar/sdk/OperationTest.java [hunk 4]
```diff
@@ -821,6 +879,34 @@ public void testCreatePassiveSellOfferOperation() throws IOException, FormatExce
         operation.toXdrBase64(AccountConverter.enableMuxed()));
   }
 
+  @Test
```
Comment (sreuland) [inline src/test/java/org/stellar/sdk/OperationTest.java:882]: nice additional coverage on this!

**Review by sreuland — APPROVED** [review]
