### PR TITLE
LiquidityPoolIDDeserializer is missing from the PageDeserializer.

### LINKED ISSUE #404: GSON parse error when fetching accounts by trustline
### What version are you using?
0.31.0

### What did you do?
Fetch accounts based on trustline. This error happens with any asset/issuer combo. Can try with any live one, such as:
AAVE
GCQEKCSJ7IQTEEOT57T5LXKEYPPEBZGODQZHUYOBW6HKNSXUXAMH376F

`        AssetTypeCreditAlphaNum asset =
                (assetCode.length() < 5)
                ? new AssetTypeCreditAlphaNum4(assetCode, assetIssuer)
                : new AssetTypeCreditAlphaNum12(assetCode, assetIssuer);
        Server server = new Server("https://horizon.stellar.org");
        Page<AccountResponse> accountsPages = server.accounts()
                                                       .forAsset(asset)
                                                       .limit(20)
                                                       .execute();
`

### What did you expect to see?
Successful fetch of data

### What did you see instead?
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is shadow.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.records[35].balances[0].liquidity_pool_id

This code worked fine in 0.28.0, it also appears to be working fine when running 0.31.0 on TESTNET, but it does not work when running on live system.

Full stack trace:
`
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is shadow.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.records[35].balances[0].liquidity_pool_id
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
                at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
                at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
                at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
                at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
                at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
                at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
                at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
                at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
                at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:89)
                at org.springframework.cloud.sleuth.autoconfig.instrument.web.LazyTracingFilter.doFilter(TraceWebServletConfiguration.java:114)
                at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
                at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
                at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
                at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
                at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
                at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
                at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
                at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
                at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
                at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
                at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
                at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
                at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
                at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
                at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
                at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
                at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
                at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
                at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
                at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
                at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
                at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
                at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
                at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
                at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
                at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
                at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
                at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
                at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
                at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
                at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
                at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
                at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423)
                at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: shadow.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.records[35].balances[0].liquidity_pool_id
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
                at shadow.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                at shadow.com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
                at shadow.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                at shadow.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
                at shadow.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
                at shadow.com.google.gson.Gson.fromJson(Gson.java:927)
                at shadow.com.google.gson.Gson.fromJson(Gson.java:994)
                at org.stellar.sdk.responses.PageDeserializer.deserialize(PageDeserializer.java:50)
                at org.stellar.sdk.responses.PageDeserializer.deserialize(PageDeserializer.java:19)
                at shadow.com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                at shadow.com.google.gson.Gson.fromJson(Gson.java:927)
                at shadow.com.google.gson.Gson.fromJson(Gson.java:892)
                at shadow.com.google.gson.Gson.fromJson(Gson.java:841)
                at org.stellar.sdk.requests.ResponseHandler.handleResponse(ResponseHandler.java:42)
                at org.stellar.sdk.requests.AccountsRequestBuilder.execute(AccountsRequestBuilder.java:163)
                at org.stellar.sdk.requests.AccountsRequestBuilder.execute(AccountsRequestBuilder.java:188)
…
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
                at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
                at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
                at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
                ... 54 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.records[35].balances[0].liquidity_pool_id
                at shadow.com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
                at shadow.com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
                at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
                ... 90 more
`

### PR DESCRIPTION
**Pull request by vinamogit**
LiquidityPoolIDDeserializer is missing from the PageDeserializer.

This fixes #404 and #421.

### CODE REVIEW

File: src/test/java/org/stellar/sdk/responses/AccountsPageDeserializerTest.java [hunk 1]
```diff
@@ -17,6 +19,16 @@ public void testDeserialize() {
     assertEquals(accountsPage.getLinks().getPrev().getHref(), "/accounts?order=desc&limit=10&cursor=1");
     assertEquals(accountsPage.getLinks().getSelf().getHref(), "/accounts?order=asc&limit=10&cursor=");
   }
+  
+  @Test
+  public void testDeserializeWithLiquidityPoolBalance() {
```
Comment (sreuland) [inline src/test/java/org/stellar/sdk/responses/AccountsPageDeserializerTest.java:24]: great test coverage, do you think also worth adding one more check on regression aspect, i.e.:

`assertEquals(accountsPage.getRecords().get(0).getBalances()[1].getLiquidityPoolID(), Optional.absent());`

style-wise, good to remove the extra lines.

File: src/main/java/org/stellar/sdk/responses/PageDeserializer.java [hunk 2]
```diff
@@ -45,6 +46,7 @@ public Page<E> deserialize(JsonElement json, Type typeOfT, JsonDeserializationCo
             .registerTypeAdapter(EffectResponse.class, new EffectDeserializer())
             .registerTypeAdapter(LiquidityPoolResponse.class, new LiquidityPoolDeserializer())
             .registerTypeAdapter(TransactionResponse.class, new TransactionDeserializer())
+            .registerTypeAdapter(LiquidityPoolID.class, new LiquidityPoolIDDeserializer())
```
Comment (sreuland) [inline src/main/java/org/stellar/sdk/responses/PageDeserializer.java:49]: Interesting, I see the same type adapter registration for LiquidityPoolID done up at the main gson instance used by all response handlers:

https://github.com/vinamogit/java-stellar-sdk/blob/fix-lp-id-deserialization-in-page/src/main/java/org/stellar/sdk/responses/GsonSingleton.java#L39

Do you know why this is not getting used by gson to resolve the LiquidityPoolID in `TradeResponse` during unmarshaling? It looks TradesRequestBuilder.execute uses the ResponseHandler which in turn uses that gson instance which includes the type registration. If re-registering here at page deser is needed, so be it, nice find!

Comment (vinamogit) [reply src/main/java/org/stellar/sdk/responses/PageDeserializer.java:49]: I don't know anything about Gson, my guess is that it's either because of generic type or because a new Gsonbuilder is used.

**Review by sreuland — APPROVED** [review]

File: src/main/java/org/stellar/sdk/responses/PageDeserializer.java (hunk 2 above)
Comment (vinamogit) [reply src/main/java/org/stellar/sdk/responses/PageDeserializer.java:49]: The thing is that there are several Gson instances, each need to know the deserializers.
We could avoid the double maintenance between GsonSingleton and PageDeserializer by using the JsonAdapter annotation on all the types which are not Page<T>.

The only type that would need to be registered with both GsonBuilders will be the TransactionDeserializer since it uses a third instance of Gson to reconciliate the memo with its memo_type.

I published a branch for comparison:
https://github.com/vinamogit/java-stellar-sdk/commit/fe9c9de32aaedc964cc60bc42718f8f15bcc8267
