### PR TITLE
#396: streamlined Asset creation to be consistent for all asset types

### LINKED ISSUE #396: Call getAsset from TrustlineCreatedEffectResponse class
What version are you using?
Version 0.30.0

What did you do?
Call method

```
  public Asset getAsset() {
    if (assetType.equals("native")) {
      return new AssetTypeNative();
    } else {
      return Asset.createNonNativeAsset(assetCode, assetIssuer);
    }
  }
```
from `TrustlineCreatedEffectResponse` class

Operation "change_trust" in block 38115883 with effect `trustline_created`
https://horizon.stellar.org/transactions/a0a65ac4d71e44fc2be2bb071645a16a577efe6258e610214ab5dc60309c9798/effects which has
"asset_type": "liquidity_pool_shares" but assetCode and assetIssuer are null. So in Asset.createNonNativeAsset(assetCode, assetIssuer); is thrown NullPointerException

```
  public static Asset createNonNativeAsset(String code, String issuer) {
    if (code.length() >= 1 && code.length() <= 4) {
      return new AssetTypeCreditAlphaNum4(code, issuer);
    } else if (code.length() >= 5 && code.length() <= 12) {
      return new AssetTypeCreditAlphaNum12(code, issuer);
    } else {
      throw new AssetCodeLengthInvalidException();
    }
  }
```

I added comment to closed issue: https://github.com/stellar/java-stellar-sdk/issues/374#issuecomment-1004622229

### PR DESCRIPTION
**Pull request by sreuland**
checked for Asset representation(native, alpha4, alpha12, pool share) consistency for any API operation/effect resource that may have possibility of holding an Asset resource which refers to liquidity pool shares via `liquidity_pool_id` and does not contain the usual non-native alpha4 or alpha12 attributes of `asset_code` and `asset_issuer`, these are the resources identified:

`
TrustlineCreatedEffectReponse
TrustlineUpdatedEffectResponse
TrustlineRemovedEffectResponse
ChangeTrustOperationResponse
`

I refactored the Asset class to provide a bit more asset-type agnostic factory methods for generating Assets which derive the type(i.e. class model), so callers do not need to have same know-how.

closes #396

### CODE REVIEW

**Comment by sreuland** [comment]
@tamirms , this could wait, can go in after #397 is done

File: src/main/java/org/stellar/sdk/Asset.java [hunk 1]
```diff
@@ -17,67 +17,68 @@
...
-   * @param liquidityPoolID provided only if type is 'liquidity_pool_shares'
+   * @param type the type of asset. 'native' and 'liquidity_pool_shares' will generate their respective asset sub-classes
+   *             null or any other value will attempt to derive the asset sub-class from code and issuer.
+   * @param code the asset code or null
+   * @param issuer the asset issuer or null
+   * @param liquidityPoolID required only if type is 'liquidity_pool_shares'
    * @return Asset
    */
   public static Asset create(String type, String code, String issuer, String liquidityPoolID) {
+    if (type == null) {
```
Comment (tamirms) [inline src/main/java/org/stellar/sdk/Asset.java:53]: what's the rationale for changing the behavior of `type` to allow null values?

previously: type the type of asset can be 'native', 'alpha4', 'alpha12' or 'liquidity_pool_shares'

Comment (tamirms) [reply src/main/java/org/stellar/sdk/Asset.java:53]: https://github.com/stellar/go/blob/d550cca61c47b1b0bd3f9cc4fe1350d6e69b0f68/services/horizon/internal/assets/main.go#L17-L21

horizon uses credit_alphanum4 and credit_alphanum12 instead of alpha4 and alpha12

Comment (sreuland) [reply src/main/java/org/stellar/sdk/Asset.java:53]: the alpha4, alpha12 type values were/are ignored, rather the asset code is introspected to determine the Asset class type, only type values of 'native' and 'liquidity_pool_shares' have effect on derived Asset class, otherwise, clients don't need to pass a specific 'alpha4, alpha12' type, for backwards compat, it's fine, if it's one of those values or null will result in the same introspection of asset code to determine Asset class.

Comment (sreuland) [reply src/main/java/org/stellar/sdk/Asset.java:53]: trying to stay with existing static factory method pattern, but one other creational pattern to consider, but thought it might be too much breaking change, is to remove the `create` methods, and replace with builder pattern, such as:
`Asset.newBuilder().withCode().withIssuer().withLiquidityPoolId().create()`

if you don't include any `withXyz()` then by default the builder creates a native.

**Review by tamirms — APPROVED** [review]
