### PR TITLE
Fix the issue where the validity of the encoded strkey is not verified in certain scenarios.

### LINKED ISSUE #540: `AccountConverter.enableMuxed()` not throwing exceptions with trailing characters of a valid mux account
### What version are you using?

`0.41.0`

### What did you do?
I am seeing a bug in the Java SDK. The AccountConverter.enableMuxed() isn't throwing the expected exception when passed a invalid mux account: `MCEO75Y6YKE53HM6N46IJYH3LK3YYFZ4QWGNUKCSSIQSH3KOAD7BEAAAAAAAAAAAPNT2W___`

Here is the code snippet.
```
package org.example;

import org.stellar.sdk.AccountConverter;

public class Main {
  public static void main(String[] args) {
    AccountConverter accountConverter = AccountConverter.enableMuxed();
    // This is a valid muxed account
    accountConverter.encode(
        "MCEO75Y6YKE53HM6N46IJYH3LK3YYFZ4QWGNUKCSSIQSH3KOAD7BEAAAAAAAAAAAPNT2W");

    // This is an invalid muxed account and we expect an IllegalArgumentException
    try {
      accountConverter.encode("MCEO75");
    } catch (IllegalArgumentException ex) {
      System.out.println("MCE075 is not valid");
      ex.printStackTrace();
    }

    // ****** PROBLEM ******
    // This is an invalid muxed account and we expect an IllegalArgumentException but nothing is
    // thrown.
    try {
      accountConverter.encode(
          "MCEO75Y6YKE53HM6N46IJYH3LK3YYFZ4QWGNUKCSSIQSH3KOAD7BEAAAAAAAAAAAPNT2W___");
    } catch (IllegalArgumentException ex) {
      System.out.println(
          "MCEO75Y6YKE53HM6N46IJYH3LK3YYFZ4QWGNUKCSSIQSH3KOAD7BEAAAAAAAAAAAPNT2W___ is not valid");
      System.out.println(ex);
    }
  }
}
```
### What did you expect to see?
The 3rd test should throw exception.

### What did you see instead?
No exception was thrown.

### PR DESCRIPTION
**Pull request by overcat**
We have replaced the base32 library, and their internal implementations are slightly different, which has caused a bug.

fix #540

### CODE REVIEW

File: src/main/java/org/stellar/sdk/StrKey.java [hunk 1]
```diff
@@ -23,7 +25,8 @@ class StrKey {
 
   public static final int ACCOUNT_ID_ADDRESS_LENGTH = 56;
   private static final byte[] b32Table = decodingTable();
-  private static final Base32 base32Codec = new Base32();
+  private static final Base32 base32Codec =
```
Comment (sreuland) [inline src/main/java/org/stellar/sdk/StrKey.java:28]: this doesn't seem to be necessary to configure with additional settings and STRICT, since `base32decode()` determines validity now, and it may lead to partial duplication of functionality. I tried reverting this line locally, and the tests still pass.

**Review by sreuland — APPROVED** [review]

**Comment by overcat** [comment]
Hi @sreuland, can you check the status? I retriggered the CI, but it was still unable to merge.
