### PR TITLE
Fix creating Memo.ReturnHash

### LINKED ISSUE #116: MemoReturnHash#toXdr sets Hash, not RetHash
https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/MemoReturnHash.java#L26

### PR DESCRIPTION
**Pull request by bartekn**
Fix #116

### CODE REVIEW

File: src/test/java/org/stellar/sdk/MemoTest.java [hunk 1]
```diff
@@ -112,7 +111,10 @@ public void testMemoHashInvalidHex() {
     @Test
     public void testMemoReturnHashSuccess() {
         MemoReturnHash memo = Memo.returnHash("4142434445464748494a4b4c");
-        assertEquals(MemoType.MEMO_RETURN, memo.toXdr().getDiscriminant());
+        org.stellar.sdk.xdr.Memo memoXdr = memo.toXdr();
```
Comment (nikhilsaraf) [inline src/test/java/org/stellar/sdk/MemoTest.java]: why not import `org.stellar.sdk.xdr.Memo` as a type directly (instead of referencing the full name here)?

Comment (bartekn) [reply src/test/java/org/stellar/sdk/MemoTest.java]: There's a class with the same name (`Memo`) in `org.stellar.sdk` package where this test file live. It would be a name conflict.

Comment (nikhilsaraf) [reply src/test/java/org/stellar/sdk/MemoTest.java]: 👍
